Add CLI `playwright` as an entry point.
microsoft/playwright-python pull request #371
Opened 2020-12-16 08:26 UTC by yanqd0

After installed with `pip install playwright`, I find there is no CLI. `python3 -m playwright --help` works, but `playwright --help` is better.

My PR add the CLI `playwright` as an setup entry point, which will be created when installing.

Reference: [Command Line Scripts — Python Packaging Tutorial](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point)

2020-12-16 08:30 UTC, yanqd0 commented
Besides, the `playwright._main.py` is not necessary.

All content in it can be moved into `playwright.__main__.py`, while replace `main()` to:

```python
if __name__ == '__main__':
    main()
```

2020-12-17 03:51 UTC, pavelfeldman approved these changes

2020-12-17 03:52 UTC, pavelfeldman commented
Looks like you need to run `pre-commit run --all-files`

2020-12-17 04:10 UTC, kumaraditya303 requested changes
Format the changes with black! @yanqd0

2020-12-17 06:35 UTC, kumaraditya303 approved these changes

2020-12-19 00:45 UTC, pavelfeldman commented
Hey, sorry, I was moving code around and you change now requires rebaseline. I uploaded the PR, is that what you had in mind for main()?

2020-12-21 02:33 UTC, yanqd0 commented
The new PR is good.

2020-12-21 02:33 UTC, closed without merging